### ISSUE TITLE
DeepBiLSTM incomplete ?

### ISSUE THREAD

**Issue by joecheriross** [carpedm20/attentive-reader-tensorflow#11]
Is DeepbiLSTM  not complete ? I was trying to figure out the code which performs the final answer prediction. I couldn't figure out that. Please help.

**Comment by carpedm20** [comment]
Sorry but nothing is complete in this repo and I don't have any plan to complete this.

**Comment by joecheriross** [comment]
ok. Thanks for the reply Taehoon.
