### ISSUE TITLE
AttributeError: 'GFile' object has no attribute 'writelines'  on tf 0.11

### ISSUE THREAD

**Issue by SeekPoint** [carpedm20/attentive-reader-tensorflow#8]
rzai@rzai00:~/prj/attentive-reader-tensorflow$ python data_utils.py data cnn
Using gpu device 0: GeForce GTX 1080 (CNMeM is disabled)
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcurand.so locally
 [*] Combining all contexts for cnn in data/cnn/questions/training ...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 380298/380298 [02:07<00:00, 2993.01it/s]
 [*] Writing data/cnn/cnn.context ...
 [*] Create vocab from data/cnn/cnn.context to data/cnn/cnn.vocab100000 ...
Creating vocabulary data/cnn/cnn.vocab100000
data_utils.py:82: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  texts = [word for word in context.lower().split() if word not in cachedStopWords]
Tokenize : -3708.7829s
 [*] Convert data in data/cnn/questions/training into vocab indicies...
  0%|                                                                                                                                                                             | 0/380298 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "data_utils.py", line 258, in <module>
    prepare_data(data_dir, dataset_name, int(vocab_size))
  File "data_utils.py", line 229, in prepare_data
    questions_to_token_ids(train_path, vocab_fname, vocab_size)
  File "data_utils.py", line 206, in questions_to_token_ids
    data_to_token_ids(fname, fname + ".ids%s" % vocab_size, vocab)
  File "data_utils.py", line 185, in data_to_token_ids
    tokens_file.writelines(results)
AttributeError: 'GFile' object has no attribute 'writelines'
rzai@rzai00:~/prj/attentive-reader-tensorflow$

**Comment by SeekPoint** [comment]
fixed by at tf 0.11 by:

diff --git a/data_utils.py b/data_utils.py
index 713abd8..2fe4069 100755
--- a/data_utils.py
+++ b/data_utils.py
@@ -35,7 +35,7 @@ from nltk.tokenize import RegexpTokenizer
 
 tokenizer = RegexpTokenizer(r'\w+')
 
-from tensorflow.python.platform import gfile
+#from tensorflow.python.platform import gfile
 
 # Regular expressions used to tokenize.
 _WORD_SPLIT = re.compile("([.,!?\"':;)(])")
@@ -76,7 +76,7 @@ def create_vocabulary(vocabulary_path, context, max_vocabulary_size,
       if None, basic_tokenizer will be used.
     normalize_digits: Boolean; if true, all digits are replaced by 0s.
   """
-  if not gfile.Exists(vocabulary_path):
+  if not os.path.exists(vocabulary_path):
     t0 = time.time()
     print("Creating vocabulary %s" % (vocabulary_path))
     texts = [word for word in context.lower().split() if word not in cachedStopWords]
@@ -104,7 +104,7 @@ def initialize_vocabulary(vocabulary_path):
   Raises:
     ValueError: if the provided vocabulary_path does not exist.
   """
-  if gfile.Exists(vocabulary_path):
+  if os.path.exists(vocabulary_path):
     vocab = corpora.Dictionary.load(vocabulary_path)
     return vocab.token2id, vocab.token2id.keys()
   else:
@@ -158,7 +158,7 @@ def data_to_token_ids(data_path, target_path, vocab,
   """
   #if not gfile.Exists(target_path):
   if True:
-    with gfile.GFile(data_path, mode="r") as data_file:
+    with open(data_path, "r") as data_file:
       counter = 0
       results = []
       for line in data_file:
@@ -181,7 +181,7 @@ def data_to_token_ids(data_path, target_path, vocab,
         len_d, len_q = len(results[2].split()), len(results[4].split())
       except:
         return
-      with gfile.GFile("%s_%s" % (target_path, len_d + len_q), mode="w") as tokens_file:
+      with open("%s_%s" % (target_path, len_d + len_q), "w") as tokens_file:
         tokens_file.writelines(results)
 
 def get_all_context(dir_name, context_fname):
@@ -216,7 +216,7 @@ def prepare_data(data_dir, dataset_name, vocab_size):
     print(" [*] Combining all contexts for %s in %s ..." % (dataset_name, train_path))
     context = get_all_context(train_path, context_fname)
   else:
-    context = gfile.GFile(context_fname, mode="r").read()
+    context = open(context_fname, "r").read()
     print(" [*] Skip combining all contexts")
 
   if not os.path.exists(vocab_fname):
(END)

**Comment by nicolettiant89** [comment]
Hi, @loveJasmine how did you solve this issue?

**Comment by SeekPoint** [comment]
see my second reply!

**Comment by nicolettiant89** [comment]
oh, Thanks a lot :) what tf version did you use to run until the end? (if you did) I see there are a lot of methods deprecated, the 0.11 isn't it?...

**Comment by SeekPoint** [comment]
yes, tf0.11

**Comment by nicolettiant89** [comment]
sorry, if i bother you @loveJasmine , but the file cells.py in "model" directory, use the method "input_size", which is deprecated in tf 0.11, in both RNNCell class and DropoutWrapper class. How did you manage that? Actually when i run the command:

python main.py --dataset cnn

the following exception fired:

> Traceback (most recent call last):
  File "main.py", line 49, in <module>
    tf.app.run()
  File "/home/nicolett/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "main.py", line 39, in main
    checkpoint_dir=FLAGS.checkpoint_dir, forward_only=FLAGS.forward_only)
  File "/home/nicolett/attentive-reader-tensorflow/model/deep_lstm.py", line 41, in __init__
    self.stacked_cell = MultiRNNCellWithSkipConn([self.cell] * depth)
  File "/home/nicolett/attentive-reader-tensorflow/model/cells.py", line 66, in __init__
    if cells[i + 1].input_size != cells[i].output_size:
AttributeError: 'DropoutWrapper' object has no attribute 'input_size'

**Comment by nicolettiant89** [comment]
@loveJasmine are you online?

**Comment by kuthedk** [comment]
so... anyone have a workaround for this now that its next to impossible to get tf 0.11?
